[build]
  functions = "netlify/functions"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm start"
  publish = "build"
  framework = "create-react-app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

